### ISSUE TITLE
How do I compile it?

### ISSUE THREAD

**Issue by fandangos** [worleydl/hdr-switcher#1]
Hi worleydl, sorry to open an issue on this project but I don't have a twitter account and have no idea how to contact you in any other form. 

I'm looking into this to be added (not officially) into Kodi. 

How do I compile this? Or do you have it already compiled for windows?

**Comment by worleydl** [comment]
VS2018 should build it, it was mostly a gutted version of the sample SDK code found on this page:  https://developer.nvidia.com/high-dynamic-range-display-development

This was very early HDR stuff and operating systems seem to have better built-in support for switching display modes now (or so I've heard, haven't played with it in a while).

**Comment by fandangos** [comment]
Nevermind, I was able to compile it after adding the nvapi64.lib file :))

**Comment by fandangos** [comment]
By the way, I had to add a few things to DeviceManager.h so I'm able to compile it

#pragma once
#pragma comment(lib, "dxgi.lib")
#pragma comment(lib, "d3d11.lib")
#include <Windows.h>
#include <DXGI.h>
#include <D3D11.h>
#include <  list>
#include <  algorithm>
#include <  string>

Remove the spaces I did this because the content wasn't showing on github. 

Also to be able to compile you need to go into disable precompiled hearder, set this to No.
Also you need to add nvapi64.lib to project proprieties -> Linker -> input and add to it. 

I believe this might help other people that want to compile it.

**Comment by worleydl** [comment]
Feel free to open a PR if you get it working with a later version of VS (or just fork and maintain things as I'm not too available to look at this stuff anymore)

I went back and looked and I was using VS2017 when I worked with this.  Sorry for the version mixup.

**Comment by fandangos** [comment]
Ok forked it. Thank you.

I'm trying to add this to kodi, if you have the time and could give me some feedback, thread here:
https://forum.kodi.tv/showthread.php?tid=344275

This would be much appreciated.
